all:
	gcc ./simple/simple.s -o ./simple/simple -nostartfiles -static
	gcc ./simple/simple_thumb.s -o ./simple/simple_thumb -nostartfiles -static
	gcc ./simple_leaks/test.c -o ./simple_leaks/test -nostartfiles
